# Generated by Django 5.0.2 on 2024-02-17 17:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("buyer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAgent",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="", max_length=13, region=None
                    ),
                ),
                ("aadhar_number", models.CharField(max_length=255)),
                (
                    "adhar_front",
                    models.ImageField(
                        default="", upload_to="delivery/delivery_agent_docs/"
                    ),
                ),
                (
                    "adhar_back",
                    models.ImageField(
                        default="", upload_to="delivery/delivery_agent_docs/"
                    ),
                ),
                ("PAN_number", models.CharField(max_length=255)),
                (
                    "PAN_front",
                    models.ImageField(
                        default="", upload_to="delivery/delivery_agent_docs/"
                    ),
                ),
                ("driving_licence", models.CharField(max_length=255)),
                (
                    "driving_licence_front",
                    models.ImageField(
                        default="", upload_to="delivery/delivery_agent_docs/"
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=255)),
                (
                    "number_plate",
                    models.ImageField(
                        default="", upload_to="delivery/delivery_agent_docs/"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("delivery_count", models.IntegerField(default=0)),
                (
                    "delivery_regions",
                    models.ManyToManyField(
                        related_name="delivery_agents", to="account.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_picked", models.BooleanField(default=False)),
                ("is_delivered", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.order"
                    ),
                ),
                (
                    "delivery_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="delivery.deliveryagent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PickDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pick_up_address", models.CharField(max_length=255)),
                (
                    "pick_up_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="", max_length=13, region=None
                    ),
                ),
                (
                    "drop_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="", max_length=13, region=None
                    ),
                ),
                ("drop_address", models.CharField(max_length=255)),
                (
                    "weight",
                    models.CharField(
                        choices=[
                            ("0kg to 2kg", "2"),
                            ("2kg to 5kg", "5"),
                            ("5kg to 6kg", "6"),
                            ("6kg to 7kg", "7"),
                            ("7kg to 8kg", "8"),
                            ("8kg to 9kg", "9"),
                            ("9kg to 10kg", "10"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.CharField(default="", max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
