# Generated by Django 5.0.2 on 2024-02-17 17:46

import django.db.models.deletion
import phonenumber_field.modelfields
import seller.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("slug", models.SlugField()),
                (
                    "logo",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="Brand_logos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(default="", max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="Categories_logos"
                    ),
                ),
                ("returnable", models.BooleanField(default=False)),
                ("replacable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seller.categories",
                    ),
                ),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("shop_name", models.CharField(default="", max_length=255)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="", max_length=13, region=None
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=seller.models.seller_logo_upload_path,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=800),
                ),
                ("gst", models.CharField(blank=True, max_length=25)),
                ("acc_no", models.CharField(blank=True, max_length=50)),
                ("ifsc_no", models.CharField(blank=True, max_length=50)),
                ("bank_name", models.CharField(blank=True, max_length=50)),
                ("benifichiery_name", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.address",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="sellers", to="seller.categories"
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seller.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_count", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "img1",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=seller.models.product_image_upload_path,
                    ),
                ),
                (
                    "img2",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=seller.models.product_image_upload_path,
                    ),
                ),
                (
                    "img3",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=seller.models.product_image_upload_path,
                    ),
                ),
                (
                    "img4",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=seller.models.product_image_upload_path,
                    ),
                ),
                (
                    "img5",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to=seller.models.product_image_upload_path,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seller.brand",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products", to="seller.categories"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seller.sellerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("s", "Small"),
                            ("m", "Medium"),
                            ("l", "Large"),
                            ("xl", "Extra Large"),
                            ("xxl", "Extra Extra Large"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("red", "Red"),
                            ("white", "White"),
                            ("black", "Black"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("orange", "Orange"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("purple", "Purple"),
                            ("grey", "Grey"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="seller.product"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seller.sellerprofile",
                    ),
                ),
            ],
        ),
    ]
